import { staticFile } from "remotion";
import type { PresentationProps } from "./Root";

/**
 * Returns the path to the props.json file via staticFile().
 *
 * The props.json file is generated by scaffold_video.py and placed in
 * the public/ directory. It contains the full PresentationProps payload
 * including slide image paths, audio paths, durations, and titles.
 *
 * Usage in remotion.config.ts or when rendering via CLI:
 *   npx remotion render Presentation out/presentation.mp4 --props=public/props.json
 *
 * Usage programmatically:
 *   const propsPath = getPropsPath();
 *   // -> "props.json" resolved through staticFile()
 */
export const getPropsPath = (): string => {
  return staticFile("props.json");
};

/**
 * Fetches and parses the props.json file at runtime.
 * This is useful for the Remotion Studio preview.
 */
export const loadProps = async (): Promise<PresentationProps> => {
  const url = getPropsPath();
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(
      `Failed to load props.json: ${response.status} ${response.statusText}`,
    );
  }

  const data: PresentationProps = await response.json();
  return data;
};
