#!/usr/bin/env python3
"""Create a working paper skeleton in one command.

Version: 2026-09-05-v1

The full workflow has ten gates and is worth every one of them on a real paper.
This script exists so the first five minutes produce something you can open,
edit and build, before you decide whether the rest is for you.

It writes a manuscript in the format the discipline expects (LaTeX for fields
that submit LaTeX, Markdown for fields that submit Word), wires in the citation
style's preamble, creates an empty bibliography with the fetch command in a
comment, seeds a plan and an issues CSV, and starts an autopilot run at the
first phase.

It writes no prose and invents no citations. Every section is a stub with a
one-line prompt saying what belongs there.

Usage:
  python scripts/quick_start.py --title "Sleep and recall in adults" --discipline psychology
  python scripts/quick_start.py --title "Attention scaling" --discipline computer-science --venue neurips
  python scripts/quick_start.py --list
"""

from __future__ import annotations

import argparse
import csv
import subprocess
import sys
from pathlib import Path

from citation_style import StyleError, load_style, render_preamble
from discipline_profile import DisciplineError, list_disciplines, load_discipline
from paper_utils import enable_utf8_stdout, now_iso, now_timestamp, slugify

BANNER = "quick_start 2026-09-05-v1"

# What each stub section asks the author for.
SECTION_PROMPTS = {
    "Abstract": "One paragraph: the question, what you did, what you found, what it means.",
    "Introduction": "The problem, why it is open, and what this paper adds. End with the contributions.",
    "Related Work": "The conversation you are joining. Group by idea, not by paper.",
    "Literature Review": "What is established, what is contested, and where the gap is.",
    "Theoretical Framework": "The theory the study uses, and what it predicts here.",
    "Theory and Hypotheses": "The mechanism, then each hypothesis it implies.",
    "Background": "The context a reader needs before the analysis.",
    "Method": "Enough detail for someone else to run this and get the same thing.",
    "Methods": "Design, participants, materials, procedure, analysis plan.",
    "Data and Methods": "Where the data came from, how they were prepared, and how they were analysed.",
    "Argument": "The claim, the evidence for it, and the reading it supports.",
    "Analysis": "The reasoning, step by step, anchored to the sources.",
    "Experiments": "Setup, baselines, metrics, and what each experiment is meant to settle.",
    "Results": "What the analysis produced. Numbers here, interpretation below.",
    "Findings": "What the data show, with evidence for each claim.",
    "Discussion": "What the results mean, and what they do not mean.",
    "Implications": "What changes for practice or policy if this holds.",
    "Limitations": "What could be wrong, and which way each limitation would push the result.",
    "Conclusion": "The claim you can now defend, and what comes next.",
    "Broader Impact": "Who is affected, and how, including the ways it could go badly.",
    "Paper Checklist": "Generated by scripts/paper_checklist.py; answer every item yourself.",
    "References": "Generated from ref.bib. Never typed by hand.",
    "Works Cited": "Generated from ref.bib. Never typed by hand.",
}

DEFAULT_PROMPT = "Say what belongs in this section, then write it."

ISSUE_COLUMNS = [
    "ID",
    "Phase",
    "Title",
    "Description",
    "Target_Citations",
    "Visualization",
    "Acceptance",
    "Status",
    "Verified_Citations",
    "Notes",
    "Depends_On",
    "Owner",
]


def section_prompt(name: str) -> str:
    return SECTION_PROMPTS.get(name, DEFAULT_PROMPT)


def build_latex(title: str, sections: list[str], style: dict, statements: list[str]) -> str:
    """Render a compilable LaTeX skeleton for the given style and sections."""
    lines = [
        f"% Generated by {BANNER} on {now_iso()}",
        "% Every section below is a stub. Replace the prompt with your own text.",
        "\\documentclass[11pt]{article}",
        "\\usepackage[utf8]{inputenc}",
        "\\usepackage[T1]{fontenc}",
        "\\usepackage{geometry}",
        "\\geometry{margin=1in}",
        "\\usepackage{graphicx}",
        "\\usepackage{booktabs}",
        "",
        render_preamble(style).rstrip(),
        "",
        f"\\title{{{title}}}",
        "\\author{Author Name\\\\Institution}",
        "\\date{\\today}",
        "",
        "\\begin{document}",
        "\\maketitle",
        "",
    ]

    for name in sections:
        if name in {"References", "Works Cited"}:
            continue
        if name == "Abstract":
            lines += ["\\begin{abstract}", f"% {section_prompt(name)}", "\\end{abstract}", ""]
            continue
        lines += [f"\\section{{{name}}}", f"% {section_prompt(name)}", ""]

    if statements:
        lines += ["\\section*{Declarations}", "% This field requires each of the following."]
        lines += [f"% - {statement}" for statement in statements]
        lines.append("")

    # biblatex prints the bibliography with its own command. A .bst backend needs
    # \bibliography{ref} here, because its \bibliographystyle line sits in the preamble.
    if style["latex_backend"] == "biblatex":
        lines.append(style["latex_bibliography_line"])
    else:
        lines.append("\\bibliography{ref}")
    lines += ["", "\\end{document}", ""]
    return "\n".join(lines)


def build_markdown(title: str, sections: list[str], style: dict, statements: list[str]) -> str:
    """Render a Markdown skeleton for the pandoc/Word path."""
    lines = [
        "---",
        f'title: "{title}"',
        "author: Author Name",
        f"date: {now_iso()[:10]}",
        "bibliography: ref.bib",
        f"csl-id: {style['csl_id']}",
        "---",
        "",
        f"<!-- Generated by {BANNER}. Every section is a stub. -->",
        "",
    ]
    for name in sections:
        lines += [f"# {name}", "", f"<!-- {section_prompt(name)} -->", ""]

    if statements:
        lines += ["# Declarations", ""]
        lines += [f"- {statement}: <!-- required by this field -->" for statement in statements]
        lines.append("")
    return "\n".join(lines)


def build_bib(style: dict) -> str:
    return "\n".join(
        [
            f"% Bibliography for this paper. Style: {style['display_name']}.",
            "%",
            "% Never write an entry by hand and never generate one from memory.",
            "% Fetch each one from a source:",
            "%   python scripts/fetch_bibtex.py --title \"<paper title>\"",
            "%   python scripts/arxiv_registry.py fetch-bibtex --help",
            "%",
            f"% This style requires, for a journal article: "
            f"{', '.join(style.get('required_fields_article') or [])}",
            "% Check every entry with:",
            f"%   python scripts/citation_style.py validate {style['style']} --bib ref.bib",
            "",
        ]
    )


def build_plan(title: str, discipline: dict, style: dict, sections: list[str], venue: str | None) -> str:
    lines = [
        f"# Plan: {title}",
        f"Generated: {now_iso()} by {BANNER}",
        "",
        "This plan is a stub. Fill it in, read it back, and only then start writing.",
        "The workflow will not leave the plan phase until a person approves it.",
        "",
        "## Setup",
        f"- Discipline: {discipline['display_name']} ({discipline['discipline']})",
        f"- Evidence model: {discipline['evidence_model']}",
        f"- Citation style: {style['display_name']} ({style['style']})",
        f"- Output format: {discipline['default_format']}",
        f"- Target venue: {venue or 'not chosen yet'}",
        "",
        "## Research question",
        "[TODO: one question, with the population and the boundary of the claim.]",
        "",
        "## Contribution",
        "[TODO: what a reader can do after this paper that they could not before.]",
        "",
        "## Outline",
    ]
    for name in sections:
        lines.append(f"- **{name}** — [TODO: {section_prompt(name)}]")

    guidelines = discipline.get("reporting_guidelines") or []
    lines += ["", "## Reporting guideline"]
    if guidelines:
        lines.append(f"[TODO: choose the one matching the design: {', '.join(guidelines)}]")
    else:
        lines.append("This field has no reporting-guideline tradition.")

    lines += ["", "## What would make this wrong", "[TODO: name the result that would falsify the claim.]", ""]
    return "\n".join(lines)


def build_issues(sections: list[str]) -> list[dict]:
    """One writing issue per section, plus the two that always come first."""
    rows = [
        {
            "ID": "R1",
            "Phase": "Research",
            "Title": "Literature harvest",
            "Description": "Find the work this paper builds on and fetch every citation from a source",
            "Target_Citations": "8",
            "Visualization": "N/A",
            "Acceptance": "ref.bib has at least 8 entries and no PLACEHOLDER_ keys",
            "Status": "TODO",
            "Verified_Citations": "0",
            "Notes": "Never write BibTeX from memory",
            "Depends_On": "",
            "Owner": "AI",
        },
        {
            "ID": "E1",
            "Phase": "Evidence",
            "Title": "Map claims to sources",
            "Description": "Assign at least one citation to every outline section before any prose is written",
            "Target_Citations": "0",
            "Visualization": "N/A",
            "Acceptance": "Every outline section has a source assigned",
            "Status": "TODO",
            "Verified_Citations": "0",
            "Notes": "",
            "Depends_On": "R1",
            "Owner": "AI",
        },
    ]
    previous = "E1"
    for index, name in enumerate(sections, start=1):
        if name in {"References", "Works Cited", "Paper Checklist"}:
            continue
        issue_id = f"W{index}"
        rows.append(
            {
                "ID": issue_id,
                "Phase": "Writing",
                "Title": name,
                "Description": section_prompt(name),
                "Target_Citations": "1",
                "Visualization": "N/A",
                "Acceptance": f"{name} says what the outline promised, with every claim sourced",
                "Status": "TODO",
                "Verified_Citations": "0",
                "Notes": "",
                "Depends_On": previous,
                "Owner": "AI",
            }
        )
        previous = issue_id
    return rows


def write_issues_csv(path: Path, rows: list[dict]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=ISSUE_COLUMNS)
        writer.writeheader()
        writer.writerows(rows)


def start_autopilot(project_dir: Path, title: str, discipline: str, style: str, output_format: str,
                    venue: str | None) -> bool:
    """Start the autopilot run. Returns False when the subprocess fails."""
    command = [
        sys.executable,
        str(Path(__file__).with_name("autopilot.py")),
        "init",
        "--project-dir",
        str(project_dir),
        "--topic",
        title,
        "--discipline",
        discipline,
        "--style",
        style,
        "--format",
        output_format,
        "--force",
    ]
    if venue:
        command += ["--venue", venue]
    result = subprocess.run(command, capture_output=True, encoding="utf-8", errors="replace")
    if result.returncode != 0:
        print(result.stdout)
        print(result.stderr, file=sys.stderr)
    return result.returncode == 0


def main() -> int:
    enable_utf8_stdout()
    parser = argparse.ArgumentParser(description="Create a working paper skeleton in one command.")
    parser.add_argument("--title", help="the working title")
    parser.add_argument("--discipline", help="a slug from scripts/discipline_profile.py list")
    parser.add_argument("--style", help="override the discipline's default citation style")
    parser.add_argument("--format", choices=["latex", "markdown"], help="override the discipline's default format")
    parser.add_argument("--venue", help="target venue slug, when there is one")
    parser.add_argument("--project-dir", help="where to create it (default: papers/<slug>)")
    parser.add_argument("--list", action="store_true", help="list the disciplines you can choose")
    parser.add_argument("--force", action="store_true", help="overwrite an existing project directory")
    args = parser.parse_args()

    if args.list:
        print("Disciplines:")
        for slug in list_disciplines():
            config = load_discipline(slug)
            print(f"  {slug:<18} {config['display_name']:<40} style={config['default_style']}")
        return 0

    if not args.title or not args.discipline:
        parser.print_help()
        print("\nerror: --title and --discipline are both required (see --list)", file=sys.stderr)
        return 2

    try:
        discipline = load_discipline(args.discipline)
    except DisciplineError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    style_slug = args.style or discipline["default_style"]
    try:
        style = load_style(style_slug)
    except StyleError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if style_slug not in (discipline.get("allowed_styles") or []):
        print(f"warning: {style_slug} is not among the styles {discipline['display_name']} normally accepts "
              f"({', '.join(discipline.get('allowed_styles') or [])})")

    output_format = args.format or ("latex" if discipline["default_format"] == "latex" else "markdown")
    slug = slugify(args.title)
    project_dir = Path(args.project_dir) if args.project_dir else Path("papers") / slug

    if project_dir.exists() and any(project_dir.iterdir()) and not args.force:
        print(f"error: {project_dir} exists and is not empty; pass --force to reuse it", file=sys.stderr)
        return 2

    for folder in ("notes", "plan", "issues", "figures"):
        (project_dir / folder).mkdir(parents=True, exist_ok=True)

    sections = discipline.get("required_sections") or ["Introduction", "Conclusion"]
    from discipline_profile import required_statements

    statements = required_statements(discipline)

    if output_format == "latex":
        manuscript = project_dir / "main.tex"
        manuscript.write_text(build_latex(args.title, sections, style, statements), encoding="utf-8")
    else:
        manuscript = project_dir / "main.md"
        manuscript.write_text(build_markdown(args.title, sections, style, statements), encoding="utf-8")

    (project_dir / "ref.bib").write_text(build_bib(style), encoding="utf-8")

    timestamp = now_timestamp()
    plan_path = project_dir / "plan" / f"{timestamp}-{slug}.md"
    plan_path.write_text(build_plan(args.title, discipline, style, sections, args.venue), encoding="utf-8")

    issues_path = project_dir / "issues" / f"{timestamp}-{slug}.csv"
    write_issues_csv(issues_path, build_issues(sections))

    # The autopilot records the submission format the field expects (docx), not the
    # source format the manuscript is written in (markdown). They differ on purpose.
    started = start_autopilot(
        project_dir, args.title, args.discipline, style_slug, discipline["default_format"], args.venue
    )

    print(f"{BANNER}: created {project_dir}\n")
    print(f"  {manuscript.relative_to(project_dir)}          {len(sections)} stub sections")
    print("  ref.bib             empty, with the fetch command in a comment")
    print(f"  {plan_path.relative_to(project_dir).as_posix()}")
    print(f"  {issues_path.relative_to(project_dir).as_posix()}")
    if started:
        print("  notes/autopilot-state.json   run started at phase 1 of 10")

    print("\nNext, in order:\n")
    print(f"  1. python scripts/discipline_profile.py requirements {args.discipline}")
    if output_format == "latex":
        print(f"  2. python scripts/compile_paper.py --project-dir {project_dir}")
    else:
        print(f"  2. python scripts/export_document.py --input {manuscript} --style {style_slug}")
    print(f"  3. python scripts/autopilot.py status --project-dir {project_dir}")
    print("\nThe skeleton builds but says nothing. That is the point: the argument is yours.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
